#! /bin/bash

echo "###############################################################"
echo "#                 Authorized access only!                     #" 
echo "# Disconnect IMMEDIATELY if you are not an authorized user!!! #"
echo "#         All actions Will be monitored and recorded          #"
echo "###############################################################"
echo "+++++++++++++++++++++++++++++++ SERVER INFO ++++++++++++++++++++++++++++++++"
echo "CPU :  $(cat /proc/cpuinfo | grep "model name"|awk -F: '{print $2}')"
echo "Memory: $(free -h | grep Mem: | awk '{print $2}' )"
echo "Swap: $(free -h | grep Swap: |awk  '{print $2}')"
echo "Disk: $(lsblk | grep -w  xvda | awk '{print $4}')"
echo "Distro: $(cat /etc/os-release| grep -w PRETTY_NAME | awk -F '"' '{print $2}') with $(uname -r)"
echo "CPU Load: $(uptime | awk -F ':' '{print $5}')"
echo "Free Disk: $(df -h | grep /dev/xvda | awk '{print $4}')"
echo "Free Memory: $(free -h | grep -w Mem: | awk '{print $4}')"
echo "Free Swap: $(free -h | grep -w Swap: | awk '{print $4}')"
echo "Public Address: $(dig +short myip.opendns.com @resolver1.opendns.com)"
echo "Private Address: $(ifconfig | grep -w broadcast | awk -F ' ' '{print $2}')"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
